// <auto-generated />
namespace Website.CoWines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_104));
        
        string IMigrationMetadata.Id
        {
            get { return "201602101053036_1.0.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
